name: Build resume

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Compile with XeLaTeX
        uses: xu-cheng/latex-action@6549dc21effb2730855a1281407ecfcececc6c1b # v4
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
          args: -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Upload PDF
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: resume-template
          path: resume.pdf
